<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select_AvailableFrom</name>
   <tag></tag>
   <elementGuidId>d6dfbea7-7646-4cff-acaa-87dcdbbce9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;availableFrom&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='availableFrom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b1c0f28-5fd0-49dc-89f0-e36efc87b458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>554eb0ba-dbb7-496b-96f9-202fe771cb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>availableFrom</value>
      <webElementGuid>b6c72420-bcb1-433f-acce-2fa7976dfb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select07: AM08: AM09: AM10: AM11: AM12: PM01: PM02: PM03: PM04: PM05: PM06: PM</value>
      <webElementGuid>78d33f09-f852-4cf9-8cfb-8fa394630a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container inner-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;mx-auto Calender-container&quot;]/div[@class=&quot;card flex justify-content-center&quot;]/div[@class=&quot;Modal&quot;]/div[@class=&quot;modal-addEvent-Container&quot;]/form[@class=&quot;form-group mx-auto&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>e3e45703-4e62-4c0c-af22-eefcd9d3256d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='availableFrom']</value>
      <webElementGuid>d7b8bd46-edc0-455f-8878-89c70fa3adb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div[2]/div/form/div/div/select</value>
      <webElementGuid>643f2fec-2132-4a86-8009-1aed75ee3626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fa572c8b-e9a9-442b-a347-48a553521700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'availableFrom' and (text() = 'Please Select07: AM08: AM09: AM10: AM11: AM12: PM01: PM02: PM03: PM04: PM05: PM06: PM' or . = 'Please Select07: AM08: AM09: AM10: AM11: AM12: PM01: PM02: PM03: PM04: PM05: PM06: PM')]</value>
      <webElementGuid>b686335c-ccc2-424d-9e9d-87e83537a635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
