<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Senior_Signup_Type</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3367a6b4-bd23-4181-84f4-85b9a1e9402a</testSuiteGuid>
   <testCaseLink>
      <guid>e6d3d310-1d35-407e-9fcd-99e6b7829f81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
<<<<<<< HEAD
      <testCaseId>Test Cases/Senior/Senior_Signup_Speak</testCaseId>
=======
      <testCaseId>Test Cases/Senior/Senior_Signup_Type</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>68877e28-60fd-4d80-a4e6-65ac8dd22a04</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Senior/Senior_SignUp_Data</testDataId>
      </testDataLink>
>>>>>>> branch 'master' of https://github.com/Yuvaraj2308/Automation_CaringConnection.git
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68c55595-b757-4261-9c5d-5e73432ae41f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9d3c43c-bd85-45ca-ada7-109b87fba7ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e07320-09fb-4360-9cc0-065749b4db6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8d02862-f687-49ad-acb3-bffd7177d0ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4bb20d9-4b2d-45dd-9d29-1638e8e8cd47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68a44726-56c4-4787-aaed-2c7f49de26a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dfc700f-6bfd-4a0b-a05c-46616a065d12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7a0ba9f-f2af-48bc-b4eb-31d698b7f78a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a626d2b8-7086-45fa-bddb-eb1448976c88</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
